[package]
name = "sensitivex"
version = "0.1.1"
description = "Sensitive X | 基于 Vue.JS + TailwindCSS + Tauri 的本地API Debug一体化平台"
authors = ["Patrick Yao"]
edition = "2021"

[lib]
name = "sensitivex_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
dirs = "6"
